// Бiльше флагов нада
var names = []; //<-- массив с именами флагов
var links = []; //<-- массив с ссылками на флаги

links[0] = "../akfub/flags/Georgia_(1918–1921).png";
links[1] = "../akfub/flags/the_Ottoman_Empire.png";
links[2] = "../akfub/flags/Bavaria.png";
links[3] = "../akfub/flags/the_Kingdom_of_the_Two_Sicilies_(1816).png";
links[4] = "../akfub/flags/Texas.png";
links[5] = "../akfub/flags/Hanover_(1837-1866).png";
links[6] = "../akfub/flags/Golden_Horde_(1339).png";
links[7] = "../akfub/flags/the_United_States_of_the_Ionian_Islands.png";
links[8] = "../akfub/flags/Taiping_Heavenly_Kingdom.png";
links[9] = "../akfub/flags/the_German_Empire.png";
links[10] = "../akfub/flags/US_26_Star_GreatStar_Flag.png";
links[11] = "../akfub/flags/Austria-Hungary_(1869-1918).png";
links[12] = "../akfub/flags/Transcaucasian_SFSR(1925-1936).png";
links[13] = "../akfub/flags/Scotland.png";
links[14] = "../akfub/flags/Rzeczpospolita.png";
links[15] = "../akfub/flags/Rwanda_(1959–1961).png";
links[16] = "../akfub/flags/Rhodesia_(1968–1979).png";
links[17] = "../akfub/flags/Republic_of_Maryland.png";
links[18] = "../akfub/flags/Napoleonic_Kingdom_of_Italy.png";
links[19] = "../akfub/flags/Merina_Kingdom.png";
links[20] = "../akfub/flags/German_Confederation.png";
links[21] = "../akfub/flags/Crimean_Khanate.png";
links[22] = "../akfub/flags/Cossack_Hetmanat.png";
links[23] = "../akfub/flags/Benin_Empire.png";

names[0] = "Georgia (1918–1921)";
names[1] = "the Ottoman Empire";
names[2] = "Bavaria";
names[3] = "the Kingdom of the Two Sicilies (1816)";
names[4] = "Texas";
names[5] = "Hanover (1837-1866)";
names[6] = "Golden Horde (1339)";
names[7] = "the United States of the Ionian Islands";
names[8] = "Taiping Heavenly Kingdom";
names[9] = "the German Empire";
names[10] = "US 26 Star Flag";
names[11] = "Austria-Hungary (1869-1918)";
names[12] = "Transcaucasian SFSR (1925-1936)";
names[13] = "Scotland";
names[14] = "Rzeczpospolita";
names[15] = "Rwanda (1959–1961)";
names[16] = "Rhodesia (1968–1979)";
names[17] = "Republic of Maryland";
names[18] = "Napoleonic Kingdom of Italy";
names[19] = "Merina Kingdom";
names[20] = "German Confederation";
names[21] = "Crimean Khanate";
names[22] = "Cossack Hetmanat";
names[23] = "Benin Empire";
